[package]
name = "truff-cli"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "truf"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
truff = { version = "0.1.0", path = "../core" }
