[package]
name = "upfind-cli"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "upf"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
upfind = { version = "0.1.0", path = "../core" }
